### PR TITLE
feat: order commands for execution time

### PR DESCRIPTION
**Pull request by baltedewit**

### CODE REVIEW

**Comment by baltedewit** [comment]
@nytamin your commit https://github.com/SuperFlyTV/casparcg-state/commit/3e0ea2c183b3fdbd67c6251829bdb506b47211e8 doesn' t pass the ci, should I rebase on master instead?

**Comment by nytamin** [comment]
In the CI report it looks like there's only a comma missing, should probably be an easy fix for you ;)

**Comment by nytamin** [comment]
I added a small fix in /develop & merged it in here, so it should be good to go now

**Comment by Julusian** [comment]
This looks fine to me

**Pull request merged**
